name: Debug LeetCode Sync

on:
  push:
    branches: [main]
  workflow_dispatch: # Erlaubt manuelles Auslösen

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Debug Environment
        run: |
          echo "Verfügbare Umgebungsvariablen:"
          env
          echo "---"
          echo "Secret Test (ohne Wert zu zeigen):"
          if [ -n "$LEETCODE_USERNAME" ]; then
            echo "LEETCODE_USERNAME ist gesetzt"
          else
            echo "LEETCODE_USERNAME ist NICHT gesetzt"
          fi
        env:
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}

      - name: Show Secrets Context
        run: |
          echo "Prüfe, ob Secret existiert (ohne Wert zu zeigen):"
          if [ "${{ secrets.LEETCODE_USERNAME != '' }}" == "true" ]; then
            echo "Secret existiert im Kontext"
          else
            echo "Secret existiert NICHT im Kontext"
          fi
