name: Sync LeetCode Solutions

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Debug Environment
        run: |
          echo "Python version:"
          python --version
          echo "Username is set:" 
          if [ -n "$LEETCODE_USERNAME" ]; then echo "Yes"; else echo "No"; fi
        env:
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}

      - name: Sync LeetCode submissions
        env:
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
        run: |
          python sync_leetcode.py

      - name: Check for new files
        run: |
          echo "Current directory contents:"
          ls -la
          if [ -d "leetcode_solutions" ]; then
            echo "LeetCode solutions directory contents:"
            ls -R leetcode_solutions/
          fi

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add leetcode_solutions/
          git diff --staged --quiet || (git commit -m "Update LeetCode solutions [skip ci]" && git push)
