name: Sync LeetCode Solutions

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # Täglich um Mitternacht
  workflow_dispatch: # Erlaubt manuelles Auslösen

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Sync LeetCode submissions
        env:
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
        run: |
          python sync_leetcode.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add leetcode_solutions/
          git diff --staged --quiet || (git commit -m "Update LeetCode solutions [skip ci]" && git push)
